title: Clément Demily
email: demily.clement@gmail.com
baseurl: ""
url: "https://clementdemily.github.io/"
twitter_username: demily_clement
github_username: clementdemily
markdown: kramdown
permalink: /:year/:month/:day/:title.html

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "docker-compose.yml",
    "docker-compose.dev.yml",
    "Dockerfile",
    "Dockerfile.dev",
  ] # files to exclude
highlighter: rouge

BASE_PATH: ""

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      title: Clément Demily

description: Notes d'un développeur

author:
  name: Clément Demily
  email: demily.clement+blog@gmail.com
  github: clementdemily
  twitter: demily_clement
  linkedin: clementdemily
  bio: Développeur Lillois
  email_md5: a4c48bb0b9e041ad0a5299f82b2b16d9

categories_path: categories.html
tags_path: tags.html
pages_path: pages.html
