FROM ruby:2.6.3-alpine3.8

WORKDIR /app

COPY Gemfile .

RUN apk add --no-cache g++ gcc make musl-dev \
	&& gem install eventmachine && \
  bundle install && \
  bundle update

COPY . .

EXPOSE 32000

CMD ["bundle", "exec", "jekyll", "serve", "-P", "32000"]