version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "32000:32000"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=clement-blog"
      - "traefik.frontend.rule=Host:clement.test"
      # - "traefik.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external:
      name: traefik
